title: Nie wiem
author: dan-tos
email: syfex.napasinski@interia.pl
description: > # this means to ignore newlines until "baseurl:"
 Niesamowity opis nie mam pojęcia co tutaj dać więc daje to.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
